### ISSUE TITLE
visualize code

### ISSUE THREAD

**Issue by kendy201124** [Event-AHU/Mamba_FETrack#2]
Hello, thank you very much for your work. Would you mind providing the visualization code for Fig5 in the paper? Thanks

**Comment by captainlong9** [comment]
> Hello, thank you very much for your work. Would you mind providing the visualization code for Fig5 in the paper? Thanks

The code of visualization has been uploaded, and the path of the code is Mamba_FETrack/lib/test/tracker/show_CAM.py
